name: Javascript

on:
  push:
    paths:
      - 'assets/**'
      - 'webpack.*.js'
      - 'package.lock'
      - '.babelrc'
      - '.eslint'

jobs:
  qaulity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run eslint:sniff
      - run: npm run stylelint:sniff
