name: PHP

on:
  push:
    paths:
      - 'src/**'
      - 'unofficial-convertkit.php'
      - 'tests/**'
      - 'composer.json'
      - '.phpcs.xml'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - run: composer install
      - run: composer run phpcs:sniff
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - run: composer install
      - run: composer run phpunit:test